Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
  	v.memory = 1024
  	v.cpus = 2
  	v.name ="Kiezmi's PC"
  end

  config.vm.box="ubuntu/xenial64"
  config.vm.synced_folder "./compartido","/compartido_vagrant"
  config.vm.synced_folder "./apache","/var/www/html"
  #config.vm.synced_folder ".","/vagrant", disable: true
  config.vm.network :forwarded_port, guest: 80, host: 6969
  config.vm.network :forwarded_port, guest: 3306, host: 7000
  #config.vm.network "private_network", ip:"192.168.1.200"
  #config.vm.network "public_network", ip:"192.168.1.250"
  config.vm.provision "shell" , path:"script.sh" 
end

